### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by monizb** [mshankr/gdykuku#1]
Hey @mshankr !
Could you please help me get started on this application? I do not know how to create a '.dev; file and I would be really glad if you could help me out on this!

**Comment by mshankr** [comment]
Basically u need to fill in the keys that are censored and purposely left out.

module.exports = {
  googleClientID: "get from https://console.developers.google.com/ set up a OAuth 2.0 Client ID and Secret"
  googleClientSecret: "get from https://console.developers.google.com/ set up a OAuth 2.0 Client ID and Secret",
  mongoURI: "set up a MongoDB its free and get the URI to connect your database",
  cookieKey: "self-created I just anyhow get my cat to type on my keyboard",
  stripePublishableKey: "Set up Stripe for a Key and secret key (don't need to activate your account, they will let u use a developer test version)",
  stripeSecretKey: "Set up Stripe for a Key and secret key (don't need to activate your account, they will let u use a developer test version)",
  sendGridKey: "Use SendGrid to do the mass email service so set up SendGrid account and API key",
  sendGridEmail: "use this email to mass send out the email. must verify with SendGrid",
  redirectDomain: "domain to redirect user to, after the user respond to the survey in your email"
}
